<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LazyBootstrap</RootNamespace>
    <AssemblyName>LazyBootstrap</AssemblyName>
    <ApplicationIcon>SOUND VOLTEX EXCEED GEAR.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyVersion>26.0.0.0</AssemblyVersion>
    <FileVersion>26.0.0.0</FileVersion>
    <InformationalVersion>25.2</InformationalVersion>
    <AssemblyTitle>Launcher for Lazy SDVX</AssemblyTitle>
    <Description>only compatible with sdvx</Description>
    <Company>LazyBootstrap - Lazy SDVX</Company>
    <Copyright>Copyright © 2025 Takanashi Ryo</Copyright>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(DesignTimeBuild)' != 'true'">
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
  </ItemGroup>

</Project>