<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <RootNamespace>LazyBootstrap</RootNamespace>
        <AssemblyName>LazyBootstrap</AssemblyName>
        <ApplicationIcon>..\Resources\vii\vii_icon.ico</ApplicationIcon>
        <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <InvariantGlobalization>false</InvariantGlobalization>
        <Version>26.5</Version>
        <AssemblyTitle>Launcher for Lazy SDVX</AssemblyTitle>
        <Description>A tool made for SDVX with spice2x</Description>
        <Company>LazyBootstrap - Lazy SDVX</Company>
        <Copyright>Copyright © 2026 Takanashi Ryo</Copyright>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(DesignTimeBuild)' != 'true'">
        <PublishAot>true</PublishAot>
        <PublishTrimmed>true</PublishTrimmed>
        <PublishSingleFile>false</PublishSingleFile>
        <SelfContained>true</SelfContained>
        
        <!--keep it false, otherwise it will crash on old Windows 10-->
        <CETCompat>false</CETCompat>
        
        <!--disable build warnings for trimming and AOT-->
        <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
        <SuppressAotAnalysisWarnings>true</SuppressAotAnalysisWarnings>
    </PropertyGroup>

    <!--bypass the trimmer for SukiUI-->
    <ItemGroup Condition="'$(Configuration)' == 'Release' and '$(DesignTimeBuild)' != 'true'">
        <TrimmerRootAssembly Include="SukiUI"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.17"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.17"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.7"/>
        <PackageReference Include="NAudio.Asio" Version="2.3.0"/>
        <PackageReference Include="Serilog" Version="4.3.1"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
        <PackageReference Include="SukiUI" Version="6.1.1"/>
        <PackageReference Include="Tomlyn" Version="2.10.1"/>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\Fonts\*.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\*.otf"/>
        <AvaloniaResource Include="Assets\Images\*.png"/>
        <AvaloniaResource Include="Assets\Images\*.jpg"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Resources\vii\vii_icon.ico">
            <Link>vii_icon.ico</Link>
        </None>
        <None Include="7Zip\7za.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>7za.exe</TargetPath>
        </None>
        <None Include="7Zip\7za.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>7za.dll</TargetPath>
        </None>
        <None Include="7Zip\7zxa.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>7zxa.dll</TargetPath>
        </None>
        <None Include="Libs\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <TargetPath>Libs\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\LazyBootstrap.MediaUpdater\MediaUpdateProtocol.cs" Link="MediaUpdate\MediaUpdateProtocol.cs"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="UI\MainWindow.*.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
